# Generated by Django 2.0.3 on 2018-04-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_test',
            name='status',
            field=models.BinaryField(default=1),
        ),
    ]
