# Generated by Django 2.0.3 on 2018-04-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_users_test_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_test',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
