# Generated by Django 2.0.3 on 2018-04-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20180407_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_test',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
