# Generated by Django 2.0.3 on 2018-04-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20180407_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_test',
            name='status',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
