# Generated by Django 2.0.3 on 2018-04-27 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_auto_20180407_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_test',
            name='status',
        ),
    ]
