# Generated by Django 2.0.3 on 2018-04-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.IntegerField(unique=True)),
                ('subject', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
